name   'treydock-cmake'
author 'treydock'
version '0.0.1'
license 'Apache License, Version 2.0'
summary 'A Puppet module that installs cmake.'
description 'A Puppet module that installs cmake.'
source 'git://github.com/treydock/puppet-cmake.git'
project_page 'http://github.com/treydock/puppet-cmake'
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency 'stahnma/epel', '>=0.0.1 <1.0.0'
